### ISSUE TITLE
支持修改开关位置？

### ISSUE THREAD

**Issue by littlee** [Tencent/vConsole#309]
旧版本可以通过写入 localStorage 修改初始化位置，最新版本没有效果
```js
localStorage.setItem('vConsole_switch_y', (window.innerHeight / 2 + ''));
new VConsole();
```
希望可以提供类似以下功能
```js
var v = new VConsole();
v.setPos({
  x: 100,
  y: 100
})
```

**Comment by jsjgjbzhang** [comment]
+1很急，希望支持

**Comment by littlee** [comment]
@jsjgjbzhang 

暂时通过给 html 元素加上高度可以解决

```css
html {
  height: 100%;
  /* 或者是 min-height: 100% */
}
```

```js
localStorage.setItem('vConsole_switch_y', (window.innerHeight / 2 + ''));
new VConsole();
```
