### ISSUE TITLE
引入 vconsole 后,无法上下移动

### ISSUE THREAD

**Issue by fushengruomengzhang** [Tencent/vConsole#342]
引入vconsole 后只能左右移动,无法上下移动. 非Vue 项目,非node 项目. 纯粹的 HTML + css + js 项目.
需要添加如下的css.才能实现各种移动
```css
html, body {
    height: 100%;
}
```
不希望通过这种方式解决这个问题,希望计算屏幕的最打分辨率 来控制 左右和上下移动的范围,或者还有更好的处理方法
